server:
  port: 10000
magic-api:
  web: /magic/web
  task:
    thread-name-prefix: magic-task- #???????
    pool:
      size: 8 #??????????CPU???
    shutdown:
      awaitTermination: false #?????????????????false
      awaitTerminationPeriod: 10s # ????????????????
  security:
    username: admin
    password: admin
  resource:
    location: /magic-api

